version: '3'

services:
  roommate:
    build:
      context: .
      dockerfile: Dockerfile.RoomMate
    image: team-propra/roommate:v1
    ports:
      - "8080:8080"
    environment:
      - "CLIENT_SECRET=${CLIENT_SECRET}"
      - "CLIENT_ID=${CLIENT_ID}"
      - "DATABASE_URL=${DATABASE_URL}"
  
  
  keymaster:
    build:
      context: .
      dockerfile: Dockerfile.KeyMaster
    image: team-propra/keymaster:v1
    ports:
      - "3000:3000"
    environment:
      - "ROOMMATE_URL=${ROOMMATE_URL}"
      - "ROOMMATE_ENDPOINT=${ROOMMATE_ENDPOINT}"
#      - "CLIENT_SECRET=${CLIENT_SECRET}" #evtl. notwendig um Zugriff auf /api/access zu bekommen? Noch nicht ausprobiert - nein
#      - "CLIENT_ID=${CLIENT_ID}"

  database:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"



