# Build stage
FROM gradle:9.7-jdk21 AS build
WORKDIR /usr/app/
COPY . .
RUN gradle bootJar

# Build Runtime Image stage
FROM eclipse-temurin:25-jdk
ENV JAR_NAME="RoomMate-prod.jar"
ENV APP_HOME=/usr/app
WORKDIR $APP_HOME
COPY --from=build $APP_HOME .
EXPOSE 8080
ENTRYPOINT ["sh", "-c", "exec java -jar $APP_HOME/build/libs/$JAR_NAME"]
