logging:
  level:
    ROOT: Warn
    org.flywaydb: DEBUG
spring:
  main:
    banner-mode: "off"
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: read:public_repo

  
  datasource:
    url: jdbc:h2:mem:postgres
    username: sa
    password:
    driver-class-name: org.h2.Driver
