apiVersion: batch/v1
kind: CronJob
metadata:
  name: roommate-image-updater
  namespace: roommate
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl
              command:
                - /bin/sh
                - -c
                - |
                  kubectl rollout restart deployment/roommate -n roommate