apiVersion: apps/v1
kind: Deployment
metadata:
  name: roommate-postgres
  namespace: roommate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roommate-postgres
  template:
    metadata:
      labels:
        app: roommate-postgres
    spec:
      containers:
        - name: roommate-postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: roommate-postgres-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: roommate-postgres-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: roommate-postgres-data
              mountPath: /var/lib/postgresql
      volumes:
        - name: roommate-postgres-data
          persistentVolumeClaim:
            claimName: roommate-postgres-data