apiVersion: v1
kind: Service
metadata:
  name: roommate-postgres-public
  namespace: roommate
spec:
  type: LoadBalancer
  selector:
    app: roommate-postgres
  ports:
    - port: 5432
      targetPort: 5432