apiVersion: apps/v1
kind: Deployment
metadata:
  name: roommate-postgres
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roommate-postgres
  template:
    metadata:
      labels:
        app: roommate-postgres
    spec:
      containers:
        - name: roommate-postgres
          image: postgres:15
          ports:
            - containerPort: {{ .Values.database.containerPort }}
          env:
          {{- if ne (toString .Values.database.containerPort) "5432" }}
            - name: PGPORT
              value: {{ .Values.database.containerPort | quote }}
          {{- end }}
          {{- if .Values.database.existingSecret }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret }}
                  key: {{ .Values.database.existingSecretKeys.user }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret }}
                  key: {{ .Values.database.existingSecretKeys.password }}
          {{- else }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: roommate-postgres-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: roommate-postgres-secrets
                  key: POSTGRES_PASSWORD
          {{- end }}
          volumeMounts:
            - name: roommate-postgres-data
              mountPath: /var/lib/postgresql
      volumes:
        - name: roommate-postgres-data
          persistentVolumeClaim:
            claimName: roommate-postgres-data
