apiVersion: v1
kind: Secret
metadata:
  name: roommate-postgres-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ required "postgres user is required" .Values.database.user | quote }}
  POSTGRES_PASSWORD: {{ required "postgres password is required" .Values.database.password | quote }}