{{- if not .Values.roommate.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: roommate-roommate-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  CLIENT_ID: {{ required "oauth client id is required" .Values.roommate.clientId | quote }}
  CLIENT_SECRET: {{ required "oauth client secret is required" .Values.roommate.clientSecret | quote }}
  DATABASE_URL: 'roommate-postgres'
  KEYMASTER_URL: 'roommate-keymaster'
  ADMIN_HANDLE: {{ required "github admin is required" .Values.roommate.adminHandle | quote }}
  POSTGRES_USER: {{ required "postgres user is required" .Values.database.user | quote }}
  POSTGRES_PASSWORD: {{ required "postgres password is required" .Values.database.password | quote }}
{{- end }}