{{- if not .Values.roommate.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: roommate-roommate-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  CLIENT_ID: {{ required "oauth client id is required" .Values.roommate.clientId | quote }}
  CLIENT_SECRET: {{ required "oauth client secret is required" .Values.roommate.clientSecret | quote }}
  OAUTH2_GITHUB_REDIRECT_URI: {{ default (printf "https://%s/login/oauth2/code/github" (required "host is required" .Values.ingress.host)) .Values.roommate.oauthRedirectUri | quote }}
  SPRING_DATASOURCE_EXTERNAL: "true"
  SPRING_DATASOURCE_URL: {{ printf "jdbc:postgresql://roommate-postgres:%v/postgres" .Values.database.port | quote }}
  DATABASE_URL: 'roommate-postgres'
  ROOMMATE_KEY_MASTER_EXTERNAL: "true"
  KEYMASTER_URL: 'roommate-keymaster'
  ROOMMATE_KEY_MASTER_PORT: {{ .Values.keymaster.port | quote }}
  ADMIN_HANDLE: {{ required "github admin is required" .Values.roommate.adminHandle | quote }}
  POSTGRES_USER: {{ required "postgres user is required" .Values.database.user | quote }}
  POSTGRES_PASSWORD: {{ required "postgres password is required" .Values.database.password | quote }}
{{- end }}
