apiVersion: v1
kind: Secret
metadata:
  name: roommate-keymaster-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  ROOMMATE_URL: 'http://roommate:8080'
  ROOMMATE_ENDPOINT: '/api/access'