apiVersion: v1
kind: Service
metadata:
  name: roommate-keymaster
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: roommate-keymaster
  ports:
    - name: http
      port: {{ .Values.keymaster.port }}
      targetPort: {{ .Values.keymaster.containerPort }}
