apiVersion: v1
kind: Service
metadata:
  name: roommate-keymaster
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: roommate-keymaster
  ports:
    - name: http
      port: 3000
      targetPort: 3000